live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x6D7070"
blue = "0x1BA6FA"
cyan = "0x73FBF1"
green = "0xB8E466"
magenta = "0xA578EA"
red = "0xFF4352"
white = "0xFEFEF8"
yellow = "0xFFD750"

[colors.cursor]
text = "0xFF261E"

[colors.normal]
black = "0x0d0d0d"
blue = "0x1BA6FA"
cyan = "0x21DEEF"
green = "0xA0E521"
magenta = "0x8763B8"
red = "0xFF301B"
white = "0xEBEBEB"
yellow = "0xFFC620"

[colors.primary]
background = "0x292C3E"
foreground = "0xEBEBEB"

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
scale_with_dpi = true
size = 8.0

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[mouse]
hide_when_typing = false

[mouse.double_click]
threshold = 300

[mouse.triple_click]
threshold = 300

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
