#!/bin/bash

ZFA_CONFIGS="$HOME/my_repos/zfa_configs"
SHELL_CONFIGS="$ZFA_CONFIGS/shell"
I3_CONFIGS="$ZFA_CONFIGS/i3"

function symbolic-link()
{
  local file_=$1
  local from=$2
  local to=$3

  rm $to/$file_ -r
  ln -s $from/$file_ $to
  echo "symbolic link of $file from $from/$file to $to/$file"
}

# ZSH config

function pull_shell_config()
{
  symbolic-link $1 $SHELL_CONFIGS $HOME
}

function pull_zsh_config()
{
  symbolic-link '.zshrc' $SHELL_CONFIGS $HOME
  symbolic-link '.oh-my-zsh' $SHELL_CONFIGS $HOME
}

function install_zsh()
{
  sudo apt-get install zsh
  # set zsh as default shell
  chsh -s /usr/bin/zsh
  echo ">>> Logout and login to your ubuntu session"
}

# i3 config
function pull_i3_config()
{
  $I3_CONFIGS/compile-i3-configs.sh
}

function install_i3()
{
  sudo apt-get remove dunst
}

function main()
{
  pull_i3_config
}

main $@