#!/bin/bash

# DEFINES & EXPORTS ALL CUSTOM ENV VARS
# PUTS THEM in PATH variable when needed

function export_dir_to_path()
{
  # echo exporting $1
  export PATH=$PATH:$1
}

function export_dir_to_path_recursively()
{
  to_export=$( find $1 -type d -printf ":%p" )
  # echo exporting_recuresively $to_export
  export PATH=$PATH$to_export
}

set -a

export_dir_to_path $HOME/.local/bin

# work directories
REPOS="$HOME/repos"
NETATMO_WORK_DIR=$REPOS
EMBEDDED="$REPOS/embedded"
CORE="$REPOS/core"

LEGRAND="$REPOS/legrand"
FIRMWARE_BINARY="$LEGRAND/firmware-binary"

FIRMWARE="$EMBEDDED/firmware"
MAGELLAN="$EMBEDDED/magellan"
M=$MAGELLAN
alias magellan=$MAGELLAN
export_dir_to_path "$MAGELLAN/apps/user/nlg-stm32/model_parser"
export_dir_to_path_recursively "$MAGELLAN/scripts"

FIRMWARE_BITCLOUD="$EMBEDDED/firmware-bitcloud"
alias firmware-bitcloud=$FIRMWARE_BITCLOUD
FIRMWARE_BITCLOUD_MAGELLAN="$MAGELLAN/modules/firmware-bitcloud"
alias firmware-bitcloud-magellan=$FIRMWARE_BITCLOUD_MAGELLAN
export_dir_to_path "$FIRMWARE_BITCLOUD_MAGELLAN/support/scripts"
export_dir_to_path "$FIRMWARE_BITCLOUD_MAGELLAN/toolchain/arm-none-eabi/bin"

## tools that are not exported
GDB_BTC_PY="$FIRMWARE_BITCLOUD/toolchain/arm-none-eabi/bin/arm-none-eabi-gdb-py"

OPENOCD_INSTALL="$FIRMWARE_BITCLOUD/doc/openocd-build/install"
OPENOCD_SCRIPTS="$OPENOCD_INSTALL/usr/share/openocd/scripts"

MAGELLAN_RELEASES="$EMBEDDED/magellan-releases"
alias magellan-releases=$MAGELLAN_RELEASES

EMBEDDED_TOOLS="$CORE/embedded-tools"
export_dir_to_path_recursively "$EMBEDDED_TOOLS/Linux"
export_dir_to_path_recursively "$EMBEDDED_TOOLS/generic-embedded/stm32_dfu"

PYTHON_EMBEDDED_TOOLS="$CORE/python-emb-tools"
alias python-emb-tools=$PYTHON_EMBEDDED_TOOLS
alias pyet=$PYTHON_EMBEDDED_TOOLS
export_dir_to_path_recursively "$PYTHON_EMBEDDED_TOOLS/python/bin"
export_dir_to_path_recursively "$PYTHON_EMBEDDED_TOOLS/python/lib"


## my directories
MY_REPOS="$HOME/my_repos"

## paths in zfa configs
ZFA_CONFIGS="$MY_REPOS/zfa_configs"
export_dir_to_path "$ZFA_CONFIGS/"
export_dir_to_path "$ZFA_CONFIGS/monitors"
export_dir_to_path_recursively "$ZFA_CONFIGS/scripts/"
SHELL_CONFIGS="$ZFA_CONFIGS/shell"
export_dir_to_path "$SHELL_CONFIGS/oh-my-zsh/.oh-my-zsh/custom/plugins/navi"
UDEV_RULES="$ZFA_CONFIGS/udev_rules"
VIM_CONFIGS="$ZFA_CONFIGS/vim"
GIT_CONFIGS="$ZFA_CONFIGS/git"
export_dir_to_path "$GIT_CONFIGS"
ZFA_CONFIGS_TOOLS="$ZFA_CONFIGS/tools"
MY_UDEV_NOTIFY_SH="$ZFA_CONFIGS_TOOLS/my-udev-notify/my-udev-notify.sh"
export_dir_to_path "$ZFA_CONFIGS_TOOLS"
export_dir_to_path "$ZFA_CONFIGS_TOOLS/git-autofixup"

I3_CONFIGS="$ZFA_CONFIGS/i3"
export_dir_to_path "$I3_CONFIGS"
I3BLOCKS_CONFIG="$I3_CONFIGS/i3blocks"
I3BLOCKS_REPO="$I3BLOCKS_CONFIG/i3blocks" # submodule
I3BLOCKS_SCRIPTS_DIR="$I3BLOCKS_CONFIG/i3blocks-contrib" # submodule
export_dir_to_path_recursively "$I3BLOCKS_SCRIPTS_DIR"

## paths in zfa sublime config
SUBLIME_CONFIG_REPO="$MY_REPOS/zfa_sublime_text"

## paths in zfa work tools
ZFA_WORK_TOOLS="$MY_REPOS/zfa_work_tools"
export_dir_to_path $ZFA_WORK_TOOLS
GDB_CONFIG="$ZFA_WORK_TOOLS/gdb_scripts"
GDB_SCRIPT="$ZFA_WORK_TOOLS/gdb_scripts/.gdbinit"
#GDB_SCRIPT="$HOME/.gdbinit"
WORK_SHELL="$ZFA_WORK_TOOLS/shell"

FLASH_SCRIPT="$ZFA_WORK_TOOLS/tmp/flash_script.jlink"
RESET_SCRIPT="$ZFA_WORK_TOOLS/tmp/reset_script.jlink"
DUMP_SCRIPT="$ZFA_WORK_TOOLS/tmp/dump_script.jlink"


## scripts needed as shell vars (for i3)
LOCK_SCRIPT="$ZFA_CONFIGS/scripts/lock.sh"
WALLPAPER_SCRIPT="$ZFA_CONFIGS/scripts/wallpaper.sh"
MONITORS_SCRIPT="$ZFA_CONFIGS/scripts/monitor.sh"
COMPILE_I3_CONFIG_SCRIPT="$I3_CONFIGS/compile-i3-configs.sh"

## third party
COOL_PUBLIC_REPOS="$MY_REPOS/cool_public_repos"
FORKS="$COOL_PUBLIC_REPOS/forks"
ANDROID_TOOLS="$COOL_PUBLIC_REPOS/android"
# export_dir_to_path_recursively "$ANDROID_TOOLS"

## my projects
PROJECTS="$MY_REPOS/projects"

GIT_BREATHER="$PROJECTS/git-breather"
export_dir_to_path $GIT_BREATHER

PREF_RENDEZ_VOUS="$PROJECTS/rendezvous-pref"
export_dir_to_path $PREF_RENDEZ_VOUS

WIRESHARK_KEYS=/home/zfadli/.wireshark/profiles/Default/zigbee_pc_keys

# poetry
export_dir_to_path_recursively "$HOME/.poetry/bin"

set +a

# NLX files with different last letter (NLF NLT NLP ..) without gateway
NLX_products=NL[FLMPTVCD]

