  vim.g.gutentags_generate_on_write = true
  vim.g.gutentags_generate_on_new = true
  vim.g.gutentags_generate_on_missing = true
  vim.g.gutentags_generate_on_empty_buffer = false
  vim.g.gutentags_ctags_extra_args = {'--tag-relative=yes', '--fields=+ailmnS'}
  vim.g.gutentags_trace = 0
  vim.cmd([[command! -nargs=0 GutentagsClearCache call system('rm ' . g:gutentags_cache_dir . '/*')]])

  vim.g.gutentags_ctags_exclude = {
       '*.git', '*.svg', '*.hg',
       '.ccls', 'ccls-cache/*',
       '*/tests/*',
       'build',
       'dist',
       '*sites/*/files/*',
       'bin',
       '*.bin',
       '*.elf',
       '*.S',
       '*.idx',
       'node_modules',
       'bower_components',
       'cache',
       'toolchain',
       'compiled',
       'docs',
       'Documentation',
       'example',
       'bundle',
       'vendor',
       '*.md',
       '*-lock.json',
       '*.lock',
       '*bundle*.js',
       '*build*.js',
       '.*rc*',
       '*.json',
       '*.min.*',
       '*.map',
       '*.bak',
       '*.zip',
       '*.pyc',
       '*.class',
       '*.sln',
       '*.Master',
       '*.csproj',
       '*.tmp',
       '*.csproj.user',
       '*.cache',
       '*.pdb',
       'tags*',
       'cscope.*',
       '*.css',
       '*.less',
       '*.scss',
       '*.exe', '*.dll',
       '*.mp3', '*.ogg', '*.flac',
       '*.swp', '*.swo',
       '*.bmp', '*.gif', '*.ico', '*.jpg', '*.png',
       '*.rar', '*.zip', '*.tar', '*.tar.gz', '*.tar.xz', '*.tar.bz2',
       '*.pdf', '*.doc', '*.docx', '*.ppt', '*.pptx',
       '**/firmware/generic/*',
       '**/firmware/constants/*',
       '**/firmware/generic-embedded/*',
       '**/firmware-bitcloud/generic-embedded/*',
       '*/nwk.c',
       '*/aps.c',
       '*/zcl.c' }
